### PR TITLE
Data updates.

### PR DESCRIPTION
**Pull request by unkdrew**

### CODE REVIEW

**Review by MitchPleaseAllWorld — COMMENTED** [review]
Are you sure about the flame hoodie? doesn't make a lot of sense with level 2 having 5 defense and 4 fitness, then is swaps at level 3 unless they've changed it since I went past level 3.

**Comment by unkdrew** [comment]
image

**Comment by unkdrew** [comment]
Maybe we got the Lv2 stats wrong

**Review by MitchPleaseAllWorld — APPROVED** [review]
must have got them wrong, I'll update in my next weekly update.

**Pull request merged**
